---
- hosts: scrapers
  sudo: yes
  vars:
    ansible_ssh_user: ubuntu 
    users:
    - mat
    - ubuntu
  tasks:
    - name: Docker is installed
      apt: name=docker.io state=present
    - name: ensure user groups exist
      group: name={{ item }} state=present
      with_items:
        "{{ users }}"
    - name: ensure user {{ item }} exists
      user: name={{ item }} group={{ item }} groups=adm,cdrom,sudo,docker append=yes
      with_items:
        "{{ users }}"
    - name: allow {{ item }} to sudo without a password
      lineinfile: "dest=/etc/sudoers state=present regexp='^{{ item }}' line='{{ item }} ALL=(ALL) NOPASSWD: ALL'"
      with_items:
        "{{ users }}"
    - name: deploy the app
      copy: src=app dest=/home/ubuntu/app owner=ubuntu group=ubuntu
    